-   name: Configure Image
    hosts: default
    become: true
    tasks:
    -   name: Install Nginx
        apt:
          update_cache: yes
          name: nginx
          state: latest
    -   name: Start nginx
        service:
          name: nginx
          enabled: true
          state: started